<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="55" started-at="2017-01-25T05:35:14Z" finished-at="2017-01-25T05:35:14Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="55" started-at="2017-01-25T05:35:14Z" finished-at="2017-01-25T05:35:14Z">
      <class name="org.truven.irnextgen.qa.testcases.Adhoc_TC01">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:org.truven.irnextgen.qa.testcases.Adhoc_TC01@66480dd7]" name="beforeSuite" is-config="true" duration-ms="1354" started-at="2017-01-25T11:05:12Z" finished-at="2017-01-25T11:05:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="startTestCase()[pri:0, instance:org.truven.irnextgen.qa.testcases.Adhoc_TC01@66480dd7]" name="startTestCase" is-config="true" duration-ms="1" started-at="2017-01-25T11:05:14Z" finished-at="2017-01-25T11:05:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method status="FAIL" signature="loginforSuccess(java.lang.String)[pri:0, instance:org.truven.irnextgen.qa.testcases.Adhoc_TC01@66480dd7]" name="loginforSuccess" duration-ms="0" started-at="2017-01-25T11:05:14Z" data-provider="fetchdata" finished-at="2017-01-25T11:05:14Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Data Provider public java.lang.Object[][] org.truven.irnextgen.qa.wrappers.ProjectSpecificWrappers.getdata() throws java.lang.Throwable must return either Object[][] or Iterator<Object>[], not class [[Ljava.lang.Object;]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Data Provider public java.lang.Object[][] org.truven.irnextgen.qa.wrappers.ProjectSpecificWrappers.getdata() throws java.lang.Throwable must return either Object[][] or Iterator<Object>[], not class [[Ljava.lang.Object;
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:133)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1020)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1110)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginforSuccess -->
        <test-method status="FAIL" signature="afterSuite()[pri:0, instance:org.truven.irnextgen.qa.testcases.Adhoc_TC01@66480dd7]" name="afterSuite" is-config="true" duration-ms="0" started-at="2017-01-25T11:05:14Z" finished-at="2017-01-25T11:05:14Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.relevantcodes.extentreports.Report.terminate(Report.java:417)
	at com.relevantcodes.extentreports.ExtentReports.close(ExtentReports.java:920)
	at org.truven.irnextgen.qa.utils.Reporter.endSuite(Reporter.java:62)
	at org.truven.irnextgen.qa.wrappers.ProjectSpecificWrappers.afterSuite(ProjectSpecificWrappers.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:357)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- org.truven.irnextgen.qa.testcases.Adhoc_TC01 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
